spring:
  profiles:
    include: oauth
  datasource:
    url: jdbc:mariadb://mit4.iptime.org:3336/naduri
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: admin
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  session:
    store-type: jdbc