#로그인 API 설정
spring:
  security:
    oauth2:
      client:
        #registration
        registration:
          #구글
          google:
            client-id: 1050608260638-e1sef209ces8vc423onmtcc2u4gf993c.apps.googleusercontent.com
            client-secret: jKeiqfuXxXBfJXDwZnxrizmo
            scope:
              - profile
              - email
          #네이버
          naver:
            client-id: DgKEnDrOPQvnn5Mmed4l
            client-secret: RpQCee2z3B
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization_grant_type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
          #카카오
          kakao:
            client-id: d3645ff3a929a34e9a95fed3b153473e
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization_grant_type: authorization_code
            scope:
              - profile
              - account_email
            client-name: Kakao
        #provider
        provider:
          #네이버
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          #카카오
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: kakao_account
